# Generated by Django 3.1.7 on 2021-03-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210304_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ber',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
