# Generated by Django 3.1.7 on 2021-03-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20210310_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sale_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
