# Generated by Django 3.1.7 on 2021-03-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_auto_20210310_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='county',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
