# Generated by Django 3.1.7 on 2021-03-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20210304_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='agent_email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contact',
            name='agent_name',
            field=models.CharField(max_length=200),
        ),
    ]
